class Rama{
	public static void main(String[] args){
		System.out.println("OHM VIGNESWARAYANAMAHA");
		System.out.println("OHM SRI LAKSHMI PADMAVATHY SAMETHA VENKATESWARAYANAMAHA");
		System.out.println("OHM SRI BHADRAVATHY SAMETHA BHAVA NARAYANA SWAMYNENAMAHA");
		System.out.println("OHM NAMAH SIVAYA");
		System.out.println("OHM SRI SAI NADHAYANAMAHA");
		System.out.println("SRI GURUBHYONNAMAHA");
		System.out.println("OHM NAMO NARAYANAYA");
		System.out.println("OHM SRI KRISHNA PARAMATMANENAMAHA");
		System.out.println("SRI RAMA CHANDRA PARABRAMHANENAMAHA");
	}
}	

/*
D:\BHAVA>javac Rama.java

D:\BHAVA>java Rama
OHM VIGNESWARAYANAMAHA
OHM SRI LAKSHMI PADMAVATHY SAMETHA VENKATESWARAYANAMAHA
OHM SRI BHADRAVATHY SAMETHA BHAVA NARAYANA SWAMYNENAMAHA
OHM NAMAH SIVAYA
OHM SRI SAI NADHAYANAMAHA
SRI GURUBHYONNAMAHA
OHM NAMO NARAYANAYA
OHM SRI KRISHNA PARAMATMANENAMAHA
SRI RAMA CHANDRA PARABRAMHANENAMAHA
*/